# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "piwigo.xcworkspace", scheme: "Screenshots")
  end
end

update_app_identifier(
  xcodeproj: "piwigo.xcodeproj", 	# Optional path to xcodeproj, will use the first .xcodeproj if not set
  plist_path: "piwigo/Info.plist", 	# Path to info plist file, relative to xcodeproj
  app_identifier: "org.piwigo" 		# The App Identifier
)

upload_to_testflight(
  skip_waiting_for_build_processing: true,
  apple_id: "472225196"
)

upload_to_app_store(
  precheck_include_in_app_purchases: false
)
