###################
# piwigoGetPiwigo #
###################
# To launch fastlane:
#	bundle exec fastlane snapshot --skip_open_summary
#
# A list of devices you want to take the screenshots from
devices([
  "iPhone X",										# 5.8-inch
  "iPad Pro (12.9-inch) (3rd generation)"			# 12.9-inch
])

#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
languages([
#   "ar",
#   "da",
#   "de",
   "en",
   "fr",
#   "id",
#   "it",
#   "ja",
#   "nl",
#   "pl",
#   "sv"
])

# The name of the scheme which contains the UI Tests
scheme("piwigoGetPiwigo")

# Where should the resulting screenshots be stored?
output_directory("./Assets/Screenshots/GetPiwigo")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# reinstall the app before producing screenshots
# reinstall_app

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
