##################
# piwigoAppStore #
##################
# Installation:
#	cd '/Users/lelievre/Privé - GitHub/Piwigo-Mobile'
#	sudo gem install -n /usr/local/bin fastlane -NV
#	fastlane init
#	export LC_ALL=en_US.UTF-8
#	export LANG=en_US.UTF-8
# 	Create a ./Gemfile in the root directory of your project
#	sudo /usr/bin/bundle update
#	sudo /usr/bin/bundle install
#
# To update fastlane:
#	sudo /usr/bin/bundle update fastlane
#
# To launch fastlane:
#	bundle exec fastlane snapshot
#
# A list of devices you want to take the screenshots from
devices([
  "iPhone SE",										# 4-inch
  "iPhone 8",										# 4.7-inch
  "iPhone 8 Plus",									# 5.5-inch
  "iPhone X",										# 5.8-inch
  "iPhone Xs Max",									# 6.5-inch
  "iPad Pro (9.7-inch)",							# 9.7-inch
  "iPad Pro (10.5-inch)",							# 10.5-inch
  "iPad Pro (11-inch)",								# 11-inch
 "iPad Pro (12.9-inch) (2nd generation)",			# 12.9-inch
  "iPad Pro (12.9-inch) (3rd generation)"			# 12.9-inch
])

#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
languages([
#   "en",
#   "da",
#   "nl",
   "fr",
#   "de",
   "id",
   "it",
#   "ja",
#   "sv"
])

# The name of the scheme which contains the UI Tests
scheme("piwigoAppStore")

# Where should the resulting screenshots be stored?
output_directory("Assets/Screenshots/AppStore")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# reinstall the app before producing screenshots
# reinstall_app

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
