#####################
# piwigoScreenshots #
#####################
# Installation:
#	cd '/Users/lelievre/Privé - GitHub/Piwigo-Mobile'
#
# Set up a complete Ruby web development environment
# https://github.com/monfresh/laptop
#	bash <(curl -s https://raw.githubusercontent.com/monfresh/laptop/master/laptop)
#
# Add GEM to PATH (in .zshrc)
#	export PATH=$PATH:/Users/lelievre/.gem/ruby/2.7.3/bin
#	export LC_ALL=en_US.UTF-8
#	export LANG=en_US.UTF-8
#   export SNAPSHOT_SIMULATOR_WAIT_FOR_BOOT_TIMEOUT=10
#	chruby ruby-2.7.3
#
#
# Install fastlane
#	gem install bundler
#   gem cleanup (from time to time to speed up fastlane)
#   bundle install
#	bundle update --bundler
#	gem install fastlane -NV
#	fastlane init
#   fastlane init swift
#   fastlane snapshot update
#	
# To locate fastlane
#	which fastlane
#
# To update screen sizes
#	bundle exec fastlane frameit download_frames
#   vi ~/.gem/ruby/2.7.3/gems/fastlane-2.228.0/snapshot/lib/snapshot/reports_generator.rb
#	vi ~/.gem/ruby/2.7.3/gems/fastlane-2.228.0/deliver/lib/deliver/app_screenshot.rb
#
# To update fastlane:
#	bundle update fastlane
#   bundle exec fastlane snapshot update
#
# To get a list of available options
#   bundle exec fastlane action deliver
# To download App Store Connect existing metadata
#   bundle exec fastlane deliver download_metadata
# To download App Store Connect existing screenshots
#   bundle exec fastlane deliver download_screenshots
# To upload screenshots only
#   bundle exec fastlane deliver --force --skip_binary_upload --skip_app_version_update --skip_metadata --overwrite_screenshots
# To upload screenshots and metadata
#   bundle exec fastlane deliver --force --skip_binary_upload --skip_app_version_update --overwrite_screenshots
#
# To produce snapshots:
#	bundle exec fastlane snapshot
#
# A list of devices you want to take the screenshots from
# https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications
devices([
# "iPhone SE (1st generation)",				# 4-inch
"iPhone SE (3rd generation)",				# 4.7-inch
"iPhone 8 Plus",							# 5.5-inch
"iPhone 16e",								# 6.1-inch
# "iPhone 13 Pro",							# Wiki
"iPhone 17 Pro",							# 6.3-inch
"iPhone 14 Plus",							# 6.5-inch
"iPhone Air",								# 6.9-inch
"iPad Pro (9.7-inch)",					# 9.7-inch
"iPad Pro (10.5-inch)",					# 10.5-inch
"iPad Pro 11-inch (M4)",					# 11-inch
"iPad Pro (12.9-inch) (2nd generation)",	# 12.9-inch
"iPad Pro 13-inch (M4)"					# 13-inch
])

# ["pt", "pt_BR"] # Portuguese with Brazilian locale
languages([
# "en-US",
# "zh-Hans",
"zh-Hant",
"da",
"nl-NL",
"fr-FR",
"de-DE",
"hu",
"it",
"ja",
"pl",
"ru",
"es-ES",
"sv"
])

# Parameters
scheme("piwigoScreenshots")
derived_data_path("DerivedData/piwigo")
test_without_building(true)
output_directory("fastlane/screenshots")
concurrent_simulators(false)
skip_open_summary(true)
number_of_retries(1)


# Command below fails with iOS +16.1, 17.x, 18.x, 26.0.1:
# See https://github.com/fastlane/fastlane/issues/22026
# and https://github.com/fastlane/fastlane/issues/21464
# override_status_bar(true)	# Enabled only for iPhone SE (1st Generation)
# override_status_bar_arguments("--time 9:41 --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100 --dataNetwork wifi")
# concurrent_simulators(true)
# With Xcode:
#	xcrun simctl status_bar booted list
#   xcrun simctl status_bar booted override --time "09:41" --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100
#   xcrun simctl status_bar booted override --time "2007-01-09T09:41:00-08:00" --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100
#
#   xcrun simctl status_bar "iPhone SE (1st generation)" override --time "09:41" --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100
#   xcrun simctl status_bar "iPhone SE (3rd generation)" override --time "09:41" --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100
#   xcrun simctl status_bar "iPhone 16e" override --time "09:41" --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100
#   xcrun simctl status_bar "iPhone 17 Pro" override --time "09:41" --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100
#   xcrun simctl status_bar "iPhone 14 Plus" override --time "09:41" --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100
#   xcrun simctl status_bar "iPhone Air" override --time "09:41" --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100
#
# Or use SimulatorStatusMagic to configure iOS 16+ simulators
# See https://github.com/shinydevelopment/SimulatorStatusMagic
# iOS 16+: Install the SimulatorStatusMagic app in the simulator
#          and apply the configuration
# iOS 17+: Compile library with Xcode
#          Launch the iOS 17+ simulator (piwigo scheme), stop app
#          Execute: ../SimulatorStatusMagic/build_and_inject.sh booted
# iOS 18+: Compile library with Xcode
#          Launch the iOS 18+ simulator (piwigo scheme), stop app
#          Execute: ../SimulatorStatusMagic/build_and_inject.sh booted
#
# clear_previous_screenshots(true)

# Arguments to pass to the app on launch.
# See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
